$terminal = foot
$bar = waybar
$notif = mako

#monitor = DP-1, 1920x1080@60, 0x0, 1
#for maximum compatibility for now:
monitor = , preferred, auto, 1

exec-once = $terminal
exec-once = $bar
exec-once = $notif

bind = SUPER, T, exec, foot
bind = SUPER, R, exec, wofi --sort-order=alphabetical

bind = SUPER, Q, killactive
bind = SUPER, F, fullscreen
bind = SUPER, V, togglefloating
bind = SUPER, P, pseudo

bind = SUPER, H, movefocus, l
bind = SUPER, L, movefocus, r
bind = SUPER, K, movefocus, u
bind = SUPER, J, movefocus, d

bind = SUPER SHIFT, H, movewindow, l
bind = SUPER SHIFT, L, movewindow, r
bind = SUPER SHIFT, K, movewindow, u
bind = SUPER SHIFT, J, movewindow, d

binde = , XF86AudioLowerVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ -5%
binde = , XF86AudioRaiseVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ +5%
binde = , XF86AudioMute, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle

binde = , XF86MonBrightnessUp, exec, brightnessctl set +5%
binde = , XF86MonBrightnessDown, exec, brightnessctl set 5%-

binde = , XF86Sleep, exec, systemctl suspend
binde = , XF86PowerOff, exec, systemctl poweroff

# binde = , XF86TouchpadToggle, exec, hyprctl keyword input:touchpad:enabled toggle