source = ~/.config/hypr/config.conf
source = ~/.config/hypr/colors/catppuccin-mocha-girlpop.conf

general {
    border_size = 2
    gaps_in = 5
    gaps_out = 10
    float_gaps = 5

    col.inactive_border = $surface1
    col.active_border = $pink $mauve 45deg

    col.nogroup_border = $surface1
    col.nogroup_border_active = $pink $mauve 45deg

    layout = dwindle
    
    resize_on_border = true
    extend_border_grab_area = 15
    hover_icon_on_border = true

    locale = en_US

    snap {
        enabled = true
    }
}

decoration {
    rounding = 15

    active_opacity = 1.0
    inactive_opacity = 0.8
    fullscreen_opacity = 1.0

    dim_modal = true
    dim_inactive = true

    dim_strength = 0.2
    dim_special = 0.2
    dim_around = 0.2

    border_part_of_window = true

    blur {
        enabled = true

        size = 3
        passes = 1

        ignore_opacity = true
        new_optimizations = true

        noise = 0.05
        contrast = 1.05
        brightness = 0.9
        vibrancy = 0.15
    }

    shadow {
        enabled = true
        color = $crust
    }
}

animations {
    enabled = true
    workspace_wraparound = true
}

input {
    numlock_by_default = true

    # ======== KEYBOARD ========
    kb_layout = us

    # ======== MOUSE ========
    sensitivity = 0.0
    accel_profile = adaptive
    scroll_method = twofinger

    touchpad {
        disable_while_typing = false
        natural_scroll = true
        middle_button_emulation = true
    }
}

group {
    col.border_active = $mauve
    col.border_inactive = $surface1

    col.border_locked_active = $mauve
    col.border_locked_inactive = $surface1

    groupbar {
        col.active = $mauve
        col.inactive = $surface1

        col.locked_active = $mauve
        col.locked_inactive = $surface1
    }
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    disable_scale_notification = true

    col.splash = $pink
}

binds {
    workspace_back_and_forth = true
}

xwayland {
    enabled = true
}

render {
    direct_scanout = 2
}

ecosystem {
    no_donation_nag = true
}

exec-once = $terminal