# ===== Catppuccin Mocha — Girlpoppy =====

$base       = rgb(1e1e2e)
$mantle    = rgb(181825)
$crust     = rgb(11111b)

$surface0  = rgb(313244)
$surface1  = rgb(45475a)

$text      = rgb(cdd6f4)
$subtext   = rgb(a6adc8)

$pink      = rgb(f5c2e7)
$peach     = rgb(fab387)
$rosewater = rgb(f5e0dc)
$mauve     = rgb(cba6f7)